# Configuration hybride pour améliorer les performances
nodeLinker: node-modules

# Cache optimisé (quasi zero-install)
enableGlobalCache: false
cacheFolder: .yarn/cache
enableInlineBuilds: true
enableMirror: false

# Améliorer les performances de résolution
compressionLevel: mixed

# Support pour les workspaces
preferInteractive: false

# Configuration pour les installations
enableNetwork: true

# Optimisations supplémentaires
nmHoistingLimits: none
nmMode: hardlinks-local
