cacheFolder: .yarn/cache

compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

enableMirror: false

enableNetwork: true

nmHoistingLimits: none

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: false

yarnPath: .yarn/releases/yarn-4.9.2-git.20250603.hash-875d3b4.cjs
