name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: yarn
          cache-dependency-path: './pcomparator/yarn.lock'

      - name: Install dependencies
        working-directory: ./pcomparator
        run: yarn install --frozen-lockfile

      - name: Lint
        working-directory: ./pcomparator
        run: yarn lint:check

      - name: Type check
        working-directory: ./pcomparator
        run: yarn typescript:check

      - name: Test
        working-directory: ./pcomparator
        run: yarn test

      - name: Build
        working-directory: ./pcomparator
        run: yarn build
        env:
          NODE_ENV: production

  release-check:
    name: Release Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: yarn
          cache-dependency-path: './yarn.lock'

      - name: Install semantic-release dependencies
        run: yarn install --frozen-lockfile

      - name: Dry run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release --dry-run
