name: QA

on:
  pull_request:
    branches:
      - canary
      - beta/release-next

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Build packages
        run: yarn build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Run tests
        run: yarn test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Run ESLint
        run: yarn lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Run typecheck
        run: yarn typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Run prettier
        run: yarn format:check

  continuous-release:
    name: Continuous Release
    if: github.repository == 'Deazl-Comparator/deazl'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/yarn-nm-install

      - name: Build packages
        run: yarn build

      - name: Release Preview Packages
        run: npx pkg-pr-new publish --compact --pnpm './packages/components' './packages/core/system' './packages/applications/shopping-lists'

      - name: Comment PR with preview links
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const { owner, repo, number } = context.issue;
            
            const comment = `## 📦 Preview Package Links
            
            Test these changes before merging:
            
            \`\`\`bash
            npm install @deazl/components@pr-${number}
            npm install @deazl/core-system@pr-${number}
            npm install @deazl/shopping-lists@pr-${number}
            \`\`\`
            
            These preview packages will be automatically cleaned up when the PR is closed.
            `;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });
